
stages:
  - build
  - deploy

hugo-build:
  image:
    name: klakegg/hugo:latest
    entrypoint: [""] # https://github.com/klakegg/docker-hugo/issues/13
  stage: build
  script:
    - cd site
    - hugo
  artifacts:
    paths:
      - site/public/

cdk-deploy:
  image: mbluemer/aws-cdk:latest
  stage: deploy
  dependencies:
    - hugo-build
  script:
    - poetry config settings.virtualenvs.create false
    - poetry install
    - cdk deploy Blog --require-approval never

